
python_library(
  name = 'all',
  sources = globs('*.py*'),
#
#  dependencies = [
#    pants('3rdparty/python:tornado'),
#    pants('3rdparty/python:twitter.common.app'),
#    pants('3rdparty/python:twitter.common.log'),
#    pants('src/main/python/apache/aurora/client/commands:all'),
#    pants('src/main/python/apache/aurora/client:base'),
#  ]
)
