
python_library(
  name = 'executors',
  sources = globs('*.py*'),
  dependencies = [
    'src/main/python/apache/aurora/common:aurora_job_key',
    'src/main/python/apache/aurora/client/commands:core',
    'src/main/python/apache/aurora/client:factory',
    'src/main/python/apache/aurora/client/api:updater_util',
  ]
)
